### ISSUE TITLE
标签页过时：<可以通过Studio的 Project properties > Advanced 标签页来设置>

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#13]
### Environment

- Documentation version: 7.0
- Part of the documentation: Manual
- Existing page: build.gradle

新版本的Studio中已经没有Project properties > Advanced 标签页
![image](https://user-images.githubusercontent.com/46985069/51683927-e63ac200-2025-11e9-914a-f2535e67feb8.png)

**Comment by lugreen** [comment]
同步遗漏，已处理
