### ISSUE TITLE
疑问：<定义JPA是否会以贪婪的方式加载引用实体的集合>

### ISSUE THREAD

**Issue by fat-rabbit-hub** [cubacn/documentation#19]
### Environment

- Documentation version: 7.0 
- Part of the documentation: 属性注解
- Existing page: 'entity_attr_annotations'

### Description of the bug or enhancement
此处的“贪婪”感觉不是能很好的理解
![image](https://user-images.githubusercontent.com/46982981/51733712-3022b700-20bd-11e9-996f-dcfae4c2890f.png)

**Comment by lugreen** [comment]
贪婪 这个译法应该是比较形象了，也是常见的计算机术语，比如 贪婪算法、正则表达式中的 贪婪匹配等。
