### ISSUE TITLE
菜单过时:<使用Studio中的 Deployment settings > WAR 界面>

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#25]
### Environment

- Documentation version:7.0
- Part of the documentation: Manual
- Existing page: war_deployment.adoc,wildfly_war_deployment.adoc，uberjar_deployment.adoc

### Description of the bug or enhancement
菜单名称过时
war_deployment.adoc文件中
![image](https://user-images.githubusercontent.com/46985069/51788429-f8993500-21b8-11e9-8a47-062dafe24686.png)

wildfly_war_deployment.adoc文件中
![image](https://user-images.githubusercontent.com/46985069/51788494-8d039780-21b9-11e9-9bb0-95ee21873672.png)

uberjar_deployment.adoc文件中
![image](https://user-images.githubusercontent.com/46985069/51788552-1e730980-21ba-11e9-8a8a-459e6007f703.png)

**Comment by lugreen** [comment]
同步遗漏，已处理
