### ISSUE TITLE
引用的xml文件无内容

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#34]
### Environment

- Documentation version:7.0
- Part of the documentation: Manual
- Existing page: heroku_war_deployment.adoc
### Description of the bug or enhancement

![image](https://user-images.githubusercontent.com/46985069/51801830-dddcc400-227d-11e9-8407-da99c94ea0e7.png)

**Comment by BryanYin** [comment]
确实无内容。等官方修复。

**Comment by lugreen** [comment]
已提交issue,官方修复后会同步过来。
