### ISSUE TITLE
语句不通顺：“<表示将记录编辑界面的打开历史记录>”

### ISSUE THREAD

**Issue by fat-rabbit-hub** [cubacn/documentation#43]
### Environment

- Documentation version: 7.0 
- Part of the documentation: 类注解 
- Existing page: entity_class_annotations

### Description of the bug or enhancement
建议使用：“表示将打开记录编辑界面的历史记录”
![image](https://user-images.githubusercontent.com/46982981/51833388-408f9780-2332-11e9-92b5-48a858c62e79.png)

**Comment by BryanYin** [comment]
不是那个意思，这里是说用了这个注解以后，会记录编辑界面的打开历史记录。
改成：表示系统将保存编辑界面的打开历史记录
