### ISSUE TITLE
图片没有加载出来

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#55]
### Environment

- Documentation version: 7.0
- Part of the documentation: bpm
- Existing page: qs_process_model_creation.adoc

### Description of the bug or enhancement
此处应该是一个图片
![image](https://user-images.githubusercontent.com/46985069/52834330-4d76fe00-311c-11e9-92ba-05fb05ede509.png)

**Comment by lugreen** [comment]
无此问题，请同步最新版。
