### ISSUE TITLE
标点错误

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#60]
### Environment

- Documentation version: 7.0
- Part of the documentation: bpm
- Existing page: service_invocation.adoc

### Description of the bug or enhancement
![image](https://user-images.githubusercontent.com/46985069/52866759-53033100-317a-11e9-9b48-2a830d3c9010.png)

**Comment by lugreen** [comment]
此处是并列关系，所以用顿号。英文中没有顿号。不是问题。
