### ISSUE TITLE
格式有误:<使用`Date` 替换标准的 CreateTs1>

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#62]
### Environment

- Documentation version: 7.0
- Part of the documentation: reporting
- Existing page: query_report

### Description of the bug or enhancement
![image](https://user-images.githubusercontent.com/46985069/52894934-f856ed00-31ec-11e9-8253-dc8ff7e28851.png)

**Comment by lugreen** [comment]
无此问题，请同步最新版本
