### ISSUE TITLE
语句不通顺：<数据透视表显示所有类型的datasets的所有属性>

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#65]
### Environment

- Documentation version: 7.0
- Part of the documentation: reporting
- Existing page: pivotTable_output

### Description of the bug or enhancement
![image](https://user-images.githubusercontent.com/46985069/52900203-ffeab600-322d-11e9-8487-570c40618bad.png)

**Comment by lugreen** [comment]
问题不存在，同步最新版
