### ISSUE TITLE
用词不当:<表格输出不需要报告模板>

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#66]
### Environment

- Documentation version: 7.0
- Part of the documentation: reporting
- Existing page: table_output

### Description of the bug or enhancement
![image](https://user-images.githubusercontent.com/46985069/52900227-61128980-322e-11e9-9365-9bcae1aedb36.png)

**Comment by lugreen** [comment]
此问题不存在，同步最新文档即可。
