### ISSUE TITLE
格式有误：<它接受`FileDescriptor``id`和 到`FileDecriptor` 实例本身的链接>

### ISSUE THREAD

**Issue by LionelWolf** [cubacn/documentation#68]
### Environment

- Documentation version: 7.0
- Part of the documentation: reporting
- Existing page: formatters

### Description of the bug or enhancement
![image](https://user-images.githubusercontent.com/46985069/52900486-2fe78880-3231-11e9-9ea1-597ccb5b6520.png)
![image](https://user-images.githubusercontent.com/46985069/52900492-4d1c5700-3231-11e9-97e1-1eb93caedd30.png)

**Comment by lugreen** [comment]
问题不存在，请同步最新版
